# Default values for zeebe-simple-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  hazelcast: 
    host: hazelcast
    port: 5701

image:
  repository: ghcr.io/camunda-community-hub/zeeqs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.1.0
  env:
    - name: spring.datasource.url
      value: jdbc:postgresql://postgres-dev:5432/zeeqs
    - name: spring.datasource.username
      value: username
    - name: spring.datasource.password
      value: password
    - name: spring.datasource.driverClassName
      value: org.postgresql.Driver
    - name: spring.jpa.properties.hibernate.dialect
      value: org.hibernate.dialect.PostgreSQLDialect

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "zeeqs"

labels: {}

initContainers: 
# Check for presence of hazelcast and zeebe
  - name: init-hazelcast
    image: busybox
    command: ['/bin/sh']
    args: ['-c', 'until (printf "GET /hazelcast/health/node-state HTTP/1.1\r\nHost: $HAZELCAST_HOST\r\n\r\n";) | nc $HAZELCAST_HOST $HAZELCAST_PORT; do echo waiting for hazelcast; sleep 2; done']
# Import Postgresql JDBC Driver
  - name: init-jdbc-postgresql
    image: busybox:1.28
    command: ['/bin/sh', '-c']
    args: ['wget --no-check-certificate https://jdbc.postgresql.org/download/postgresql-42.2.12.jar -O /libs/postgresql-42.2.12.jar; ls -al']
    volumeMounts:
      - name: libs
        mountPath: /libs/

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 9000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
